#!/usr/bin/env bash
set -ex
cd -- "$(dirname "$BASH_SOURCE")"
git pull origin master
sudo kextunload -bundle-id com.apple.driver.AppleUSBFTDI
sload flash kernel/latest
sload program userland/latest
sload burnfuses --wdt --bor
sudo kextload -bundle-id com.apple.driver.AppleUSBFTDI
